# Generated by Django 4.1.7 on 2023-06-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("konta", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
